language: python
python:
    - "3.6"

install:
    # install latest release version
    - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest |grep -E 'browser_download_url.*hugo_[0-9.]*_Linux-64bit.deb' | xargs wget
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    - rm -rf public 2> /dev/null

script:
    - /usr/local/bin/hugo
 
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    on:
        branch: master
    local_dir: public
    repo: chaosdancing/chaosdancing.github.io
    target_branch: master

    