language: python
python:
    - "3.6"

install:
    - pip install Pygments
    - rm -rf public || exit 0

script:
    - chmod 700 bin/hugo
    - bin/hugo -t even
 
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    on:
        branch: master
    local_dir: public
    repo: chaosdancing/chaosdancing.github.io
    target_branch: master

notifications:
  email:
    recipients:
      - whoisyoursuperman@gmail.com
    on_success: never # default: change
    on_failure: always # default: always