sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: 301950233d59137e2a2ee3614b6d31823d9a4eeb
    on:
        branch: master
    local_dir: public
    repo: chaosdancing/chaosdancing.github.io
    target_branch: master
    email: whoisyoursuperman@gmail.com
    name: chaosdancing
